import os
import json
import asyncio

from pydantic import BaseModel
from typing import Dict, Any, List
from huggingface_hub import InferenceClient

from src.pathology_vlm_client import PathologyVLMClient


class CasePayload(BaseModel):
    case_id: str
    clinical_history: str
    image_metadata: Dict[str, Any]


class PathologyOrchestrator:
    def __init__(self):
        self.hf_token = os.getenv("HF_TOKEN")
        self.client = InferenceClient(token=self.hf_token)

        # New: client for the PA-LLaVA service
        self.pathology_vlm = PathologyVLMClient()

        # Existing text-only fallback model pool
        self.model_pool: List[str] = [
            "meta-llama/Meta-Llama-3-8B-Instruct",
            "Qwen/Qwen2.5-7B-Instruct",
            "mistralai/Mistral-7B-Instruct-v0.3",
        ]

    async def process_case(self, payload: CasePayload) -> Dict[str, Any]:
        image_source = payload.image_metadata.get("image_url", "")
        roi_snapshot = payload.image_metadata.get("roi_snapshot")
        roi_snapshot_detected = roi_snapshot is not None and roi_snapshot != ""

        user_prompt = payload.clinical_history
        ehr_context = ""

        try:
            parsed_history = json.loads(payload.clinical_history)
            user_prompt = parsed_history.get("user_prompt", "")

            profile = parsed_history.get("ehr_profile", {})

            ehr_context = (
                f"--- ELECTRONIC HEALTH RECORD (EHR) REGISTERED PROFILE ---\n"
                f"• Patient Demographics: Age {profile.get('age', 'N/A')} | "
                f"Sex: {profile.get('sex', 'N/A')}\n"
                f"• Molecular/Biomarker Assays: {profile.get('biomarkers', 'None listed')}\n"
                f"• Background History Logs: {profile.get('summary_notes', 'None recorded')}\n"
            )

            if profile.get("attached_document_raw"):
                ehr_context += (
                    f"• Attached Diagnostic File Contents:\n"
                    f"{profile.get('attached_document_raw')}\n"
                )

            ehr_context += "----------------------------------------------------------\n"

        except Exception as e:
            print(f"[Orchestrator Parse Error Log]: {str(e)}")

        # ---------------------------------------------------------------------
        # NEW PA-LLaVA BRANCH
        # ---------------------------------------------------------------------
        # If the user selected an ROI and USE_PATHOLOGY_VLM=true,
        # send the real ROI image to the pathology VLM service.
        # If this succeeds, return immediately and DO NOT use the text-only HF path.
        # ---------------------------------------------------------------------
        if roi_snapshot_detected and self.pathology_vlm.enabled:
            try:
                print("[Orchestrator Log]: Sending ROI to pathology VLM service...")

                vlm_result = await asyncio.to_thread(
                    self.pathology_vlm.ask_roi,
                    roi_snapshot,
                    user_prompt,
                    ehr_context,
                    payload.case_id,
                )

                answer = vlm_result.get("answer", "")

                if not answer:
                    answer = "PA-LLaVA returned no parsed answer."

                final_text = (
                    f"{answer}\n\n"
                    "**Note:** This response was generated by PA-LLaVA from the selected ROI only, "
                    "not from the full whole-slide image. Research prototype only; not for clinical diagnosis."
                )

                return {
                    "status": "success",
                    "case_id": payload.case_id,
                    "active_model": vlm_result.get("model", "PA-LLaVA"),
                    "visual_input": "selected_roi",
                    "model_output": [
                        {
                            "generated_text": final_text
                        }
                    ],
                }

            except Exception as e:
                print(f"[Orchestrator Warning]: Pathology VLM failed: {str(e)}")

                # Return a visible error instead of silently falling back.
                # This helps you debug whether PA-LLaVA is actually being used.
                return {
                    "status": "error",
                    "case_id": payload.case_id,
                    "detail": (
                        "The selected ROI was received, but the PA-LLaVA/pathology "
                        f"VLM service failed. Error: {str(e)}"
                    ),
                }

        # ---------------------------------------------------------------------
        # NO ROI SELECTED
        # ---------------------------------------------------------------------
        # This MVP is now configured to use PA-LLaVA for ROI-based visual analysis.
        # If there is no ROI, do not fall back to the old text-only Hugging Face path.
        # The old fallback can produce fluent but non-image-grounded summaries and may
        # also fail if HF_TOKEN is missing/invalid.
        # ---------------------------------------------------------------------
        if not roi_snapshot_detected:
            return {
                "status": "error",
                "case_id": payload.case_id,
                "detail": (
                    "No ROI is currently selected. Please select a region on the image first, "
                    "then ask your question. The selected ROI will remain active for follow-up "
                    "questions until you load a new image or select a different ROI."
                ),
            }

        # ---------------------------------------------------------------------
        # OLD HUGGING FACE TEXT-ONLY FALLBACK
        # ---------------------------------------------------------------------
        # This is used when:
        # 1. no ROI was selected, or
        # 2. USE_PATHOLOGY_VLM=false
        # ---------------------------------------------------------------------
        if not self.hf_token:
            return {
                "status": "error",
                "detail": (
                    "HF_TOKEN is missing. Either set HF_TOKEN for the text-only "
                    "fallback, or select an ROI and set USE_PATHOLOGY_VLM=true."
                ),
            }

        system_instruction = (
            "You are PathChat, a world-class multimodal computational pathology AI "
            "generalist assistant. Cross-reference the explicit EHR profile parameters "
            "with the specified tissue specimen metrics and requested spatial query to "
            "generate professional, accurate clinical insights."
        )

        prompt_payload = f"Case Study ID: {payload.case_id}\n"

        if ehr_context:
            prompt_payload += ehr_context

        prompt_payload += f"Base Whole Slide Image: {image_source}\n"

        if roi_snapshot_detected:
            prompt_payload += (
                "Spatial Annotation: User has isolated a high-power field focus "
                "block coordinate region.\n"
            )

        prompt_payload += (
            f"Diagnostic User Query: {user_prompt}\n\n"
            "Formulate Pathology Assessment Report:"
        )

        last_error = ""

        for model_id in self.model_pool:
            try:
                print(f"[Orchestrator Log]: Attempting inference on {model_id}...")

                chat_completion = self.client.chat_completion(
                    model=model_id,
                    messages=[
                        {"role": "system", "content": system_instruction},
                        {"role": "user", "content": prompt_payload},
                    ],
                    max_tokens=450,
                    temperature=0.2,
                )

                response_text = chat_completion.choices[0].message.content

                print(f"[Orchestrator Log]: Success using {model_id}")

                return {
                    "status": "success",
                    "case_id": payload.case_id,
                    "active_model": model_id,
                    "visual_input": "text_only_fallback",
                    "model_output": [
                        {
                            "generated_text": (
                                f"{response_text}\n\n"
                                "**Note:** This was generated by the text-only fallback. "
                                "The selected image/ROI was not directly analyzed by a "
                                "vision-language pathology model."
                            )
                        }
                    ],
                }

            except Exception as e:
                last_error = str(e)
                print(
                    f"[Orchestrator Warning]: Model {model_id} failed or unavailable. "
                    "Trying fallback..."
                )
                continue

        return {
            "status": "error",
            "detail": (
                "All available models in the fallback cluster pool failed. "
                f"Last reported error: {last_error}"
            ),
        }
